### ISSUE TITLE
zero-units

### ISSUE THREAD

**Issue by toptalo** [Ensighten/grunt-spritesmith#156] opened 2016-01-15 16:33 UTC
Hello!
Is it possible to remove units when a value is 0

from
```css
background-position:0px -94px;
```

to 
```css
background-position:0 -94px;
```

**Comment by twolfson** [comment] 2016-01-15 17:46
This is a duplicate of https://github.com/Ensighten/grunt-spritesmith/issues/89, https://github.com/twolfson/spritesheet-templates/pull/43, and https://github.com/twolfson/spritesheet-templates/issues/11.

We suggest that this is entering CSS optimization territory and encourage developers to use another CSS optimization task after `spritesmith` to handle reducing variable sizes (e.g. `0px` -> `0`). Here are some tools to evaluate:

- https://www.npmjs.com/package/grunt-csso
    - Wrapper for http://bem.info/tools/csso/
- https://github.com/begriffs/css-ratiocinator

**Closed by twolfson** 2016-01-15 17:46 UTC
