### ISSUE TITLE
how to add the the image md5 hash on the  end of the background-image?

### ISSUE THREAD

**Issue by phpjoe** [Ensighten/grunt-spritesmith#122] opened 2015-03-31 06:49 UTC
hi , 
I am sorry about my english.
I have a issue,when i add a image to my sprite,the spritesmith create the new css for me ,but the brower get the cache of the sprite image,so,I want to add a random to the of the image in the css,like "$brand-image: '../../images/order.sprite.png?v=20151022019'",but How can I do?
It is best to add the md5 hash string of the sprite image.

**Comment by twolfson** [comment] 2015-04-01 04:34
This is a duplicate of https://github.com/Ensighten/grunt-spritesmith/issues/27 . Please see the example provided there.

**Closed by twolfson** 2015-04-01 04:34 UTC
